apiVersion: v1
kind: Secret
metadata:
  name: "{{.Release.Name}}-db-secret"
type: Opaque
stringData:
  # Database connection string
  # Format: postgresql://username:password@hostname:port/database
  DATABASE_URL: "{{.Values.databaseUrl}}"
