apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{.Release.Name}}-db-secret"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager # Reference to your SecretStore
    kind: SecretStore
  target:
    name: "{{.Release.Name}}-db-secret"
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{.Values.databaseSecretArn}} # ARN or name of secret in AWS Secrets Manager
