apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{.Release.Name}}-config"
data:
  # pg_tileserv configuration
  TS_HTTPHOST: "0.0.0.0"
  TS_HTTPPORT: "7800"
  TS_BASEPATH: "/"
  TS_CORS_ORIGINS: "*"
  TS_DEFAULT_RESOLUTION: "256"
  TS_DEFAULT_BUFFER: "64"
