apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
spec:
  selector:
    app: pg-tileserv
    tenant: {{.Release.Name}}
    env: {{.Values.env}}
  ports:
    - protocol: TCP
      port: 7800
      targetPort: 7800
